/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */

package accounts


import "magictelecomapi/models"

/*
 * Interface for the ACCOUNTS_IMPL
 */
type ACCOUNTS interface {
    CreateCallerLocations (string, *models.CallerLocationForm) (interface{}, error)

    GetCallerLocationById (string, int) (interface{}, error)

    DeleteCallerLocations (string) (string, error)

    UpdateCallerLocationById (string, int, *models.CallerLocationForm) (string, error)

    DeleteCallerLocationById (string, int) (string, error)

    GetCallerLocations (string, *int, *int) (interface{}, error)

    GetAccounts (*int, *int, *string) (interface{}, error)

    CreateAccount (*models.AccountForm) (interface{}, error)

    DeleteAccount (string) (string, error)

    GetAccount (string) (interface{}, error)

    UpdateAccount (string, *models.AccountForm) (string, error)

    DeleteCdrs (string) (string, error)

    GetCdrs (string, *int, *int, *string) (interface{}, error)

    CreateCdrs (string, *models.CdrForm) (interface{}, error)

    GetCdrById (string, string) (interface{}, error)

    DeleteCdrById (string, string) (string, error)

    DeleteDids (string) (string, error)

    DeleteTelephoneNumber (string, string) (string, error)

    GetTelephoneNumber (string, string) (interface{}, error)

    UpdateTelephoneNumber (string, string, *models.TelephoneNumberForm) (error)

    GetDids (string, *int, *int, *string) (interface{}, error)

    DeleteTrunks (string) (string, error)

    GetTrunks (string, *int, *int, *string) (interface{}, error)

    DeleteTrunkById (string, string) (string, error)

    GetTrunkById (string, string) (interface{}, error)

    DeleteCarts (string) (error)

    GetCarts (string, *int, *int, *string, *string) (interface{}, error)

    CreateCarts (string) (interface{}, error)

    DeleteCart (string, string) (error)

    GetCart (string, string) (interface{}, error)

    CreateCartCheckout (string, string, *models.CartCheckoutForm) (interface{}, error)

    DeleteItems (string, int) (string, error)

    GetItems (string, int, *int, *int) (interface{}, error)

    CreateItems (string, int, *models.ItemForm) (interface{}, error)

    DeleteItem (string, int, int) (string, error)

    GetItem (string, int, int) (interface{}, error)

    GetOrders (string, *int, *int, *string) (interface{}, error)

    GetOrder (string, int) (interface{}, error)

    UpdateTrunk (string, int, *models.TrunkForm) (string, error)

    GetAccessTokens (string, *int, *int) (interface{}, error)

    DeleteAccessToken (string, string) (string, error)

    GetAccessToken (string, string) (interface{}, error)

    UpdateAccessToken (string, string, *models.TokenForm) (string, error)

    CreateAccessTokens (string, *models.TokenForm) (interface{}, error)
}

/*
 * Factory for the ACCOUNTS interaface returning ACCOUNTS_IMPL
 */
func NewACCOUNTS() ACCOUNTS {
    return &ACCOUNTS_IMPL{}
}