/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */

package didsproducts


/*
 * Interface for the DIDSPRODUCTS_IMPL
 */
type DIDSPRODUCTS interface {
    GetDids (*int, *int, *string) (interface{}, error)

    GetDidsByPhoneNumber (string) (interface{}, error)

    GetLocations (*int, *int, *string) (interface{}, error)

    GetLocationByHandle (string) (interface{}, error)

    GetTrunks (*int, *int) (interface{}, error)

    GetTrunkByHandle (string) (interface{}, error)

    GetCountriesByTrunk (int, int) (interface{}, error)
}

/*
 * Factory for the DIDSPRODUCTS interaface returning DIDSPRODUCTS_IMPL
 */
func NewDIDSPRODUCTS() DIDSPRODUCTS {
    return &DIDSPRODUCTS_IMPL{}
}