/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */

package dids


/*
 * Interface for the DIDS_IMPL
 */
type DIDS interface {
    GetCountries (*int, *int) (interface{}, error)

    GetCountryByIso2 (string) (interface{}, error)

    GetRegions (string, *int, *int) (interface{}, error)

    GetRegionsByHandle (string, string) (interface{}, error)
}

/*
 * Factory for the DIDS interaface returning DIDS_IMPL
 */
func NewDIDS() DIDS {
    return &DIDS_IMPL{}
}