/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */

package models


/*
 * Structure for the custom type Cdrs
 */
type Cdrs struct {
    UserId          string          `json:"user_id"` //TODO: Write general description for this field
    ServiceType     string          `json:"service_type"` //TODO: Write general description for this field
    StartDate       string          `json:"start_date"` //TODO: Write general description for this field
    EndDate         string          `json:"end_date"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CartCheckoutForm
 */
type CartCheckoutForm struct {
    Checkout        Checkout        `json:"checkout"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Checkout
 */
type Checkout struct {
    ExternalOrderReference   string          `json:"external_order_reference"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type TokenForm
 */
type TokenForm struct {
    Token           Token           `json:"token"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CallerLocationResponse
 */
type CallerLocationResponse struct {
    Code            int             `json:"code"` //TODO: Write general description for this field
    Data            CallerLocation  `json:"data"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AccountForm
 */
type AccountForm struct {
    Account         Account         `json:"account"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CdrForm
 */
type CdrForm struct {
    Cdrs            Cdrs            `json:"cdrs"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type TrunkForm
 */
type TrunkForm struct {
    Trunk           Trunk           `json:"trunk"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Trunk
 */
type Trunk struct {
    SipEndPointUri    string          `json:"sip_end_point_uri"` //TODO: Write general description for this field
    Description       string          `json:"description"` //TODO: Write general description for this field
    Routing           Routing         `json:"_routing"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Routing
 */
type Routing struct {
    RoutingBase     // Anonymous member to emulate model inheritence
    SipUser         string          `json:"sip_user"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Endpoint
 */
type Endpoint struct {
    Uri             string          `json:"uri"` //TODO: Write general description for this field
    Attrs           string          `json:"attrs"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CallerLocationsResponse
 */
type CallerLocationsResponse struct {
    Code            int             `json:"code"` //TODO: Write general description for this field
    Data            Data            `json:"data"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Data
 */
type Data struct {
    Limit           int             `json:"limit"` //TODO: Write general description for this field
    Page            int             `json:"page"` //TODO: Write general description for this field
    Results         []*CallerLocation `json:"results"` //TODO: Write general description for this field
    Total           int             `json:"total"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CallerLocation
 */
type CallerLocation struct {
    Name            string          `json:"name"` //Location Name
    Address         string          `json:"address"` //Address
    City            string          `json:"city"` //City
    Region          string          `json:"region"` //Region
    PostalCode      int             `json:"postal_code"` //Postal Code
    UnitType        string          `json:"unit_type"` //Unit Type
    UnitNumber      int             `json:"unit_number"` //Unit Number
    Country         string          `json:"country"` //Country Name
}

/*
 * Structure for the custom type CallerLocationForm
 */
type CallerLocationForm struct {
    CallerLocation  CallerLocation  `json:"caller_location"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Account
 */
type Account struct {
    Number          string          `json:"number"` //TODO: Write general description for this field
    Roles           []string        `json:"roles"` //TODO: Write general description for this field
    Email           string          `json:"email"` //TODO: Write general description for this field
    ContactNumber   string          `json:"contact_number"` //TODO: Write general description for this field
    Firstname       string          `json:"firstname"` //TODO: Write general description for this field
    Lastname        string          `json:"lastname"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type TelephoneNumberForm
 */
type TelephoneNumberForm struct {
    TelephoneNumber  TelephoneNumber `json:"telephone_number"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type ItemForm
 */
type ItemForm struct {
    Item            Item            `json:"item"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Item
 */
type Item struct {
    ItemType        string          `json:"item_type"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type TrunkItem
 */
type TrunkItem struct {
    Item            // Anonymous member to emulate model inheritence
    Channels        int             `json:"channels"` //TODO: Write general description for this field
    TrunkHandle     string          `json:"trunk_handle"` //TODO: Write general description for this field
    SipUri          string          `json:"sip_uri"` //TODO: Write general description for this field
    Attributes      string          `json:"attributes"` //TODO: Write general description for this field
    Routing         Routing         `json:"_routing"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type DidItem
 */
type DidItem struct {
    Item             // Anonymous member to emulate model inheritence
    PhoneNumber      string          `json:"phone_number"` //TODO: Write general description for this field
    TrunkId          int             `json:"trunk_id"` //TODO: Write general description for this field
    DidTypeHandle    string          `json:"did_type_handle"` //TODO: Write general description for this field
    CallerLocation   CallerLocation  `json:"_caller_location,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LocationItem
 */
type LocationItem struct {
    Item             // Anonymous member to emulate model inheritence
    LocationHandle   string          `json:"location_handle"` //TODO: Write general description for this field
    Quantity         int             `json:"quantity"` //TODO: Write general description for this field
    Attributes       string          `json:"attributes"` //TODO: Write general description for this field
    DidTypeHandle    string          `json:"did_type_handle"` //TODO: Write general description for this field
    TrunkId          int             `json:"trunk_id"` //TODO: Write general description for this field
    CallerLocation   CallerLocation  `json:"_caller_location,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type RoutingBase
 */
type RoutingBase struct {
    Logic           string          `json:"logic"` //TODO: Write general description for this field
    Endpoints       []*Endpoint     `json:"endpoints"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type TelephoneNumber
 */
type TelephoneNumber struct {
    TrunkId           int             `json:"trunk_id"` //TODO: Write general description for this field
    SipEndPointUri    string          `json:"sip_end_point_uri"` //TODO: Write general description for this field
    Alias             string          `json:"alias"` //TODO: Write general description for this field
    Channels          int             `json:"channels"` //TODO: Write general description for this field
    Routing           RoutingBase     `json:"_routing"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Token
 */
type Token struct {
    IsActive        bool            `json:"is_active"` //TODO: Write general description for this field
}
