/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */

package magictelecomapi

/** The base Uri for API calls */
const BASEURI string = "https://api.magictelecom.com/app_dev.php"

var Config struct {
    /** API Token */
    /** Replace the value of XAuthToken with an appropriate value */
    XAuthToken string
}
