/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */
package users

import(
    "github.com/apimatic/unirest-go"
    "magictelecomapi"
    "magictelecomapi/apihelper"

)
/*
 * Client structure as interface implementation
 */
type USERS_IMPL struct { }

/**
 * Allow clients to test authentication.
 * @return	Returns the interface{} response from the API call
 */
func (me *USERS_IMPL) GetAuthentications () (interface{}, error) {
    //the base uri for api requests
    queryBuilder := magictelecomapi.BASEURI;
        
    //prepare query string for API call
    queryBuilder = queryBuilder + "/authentications"

    //variable to hold errors
    var err error = nil
    //validate and preprocess url
    queryBuilder, err = apihelper.CleanUrl(queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }

    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "accept" : "application/json",
        "X-Auth-Token" : magictelecomapi.Config.XAuthToken,
    }

    //prepare API request
    request := unirest.Get(queryBuilder, headers)
    //and invoke the API call request to fetch the response
    response, err := unirest.AsString(request);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (response.Code == 401) {
        err = apihelper.NewAPIError("You are not authenticated", response.Code, response.RawBody)
    } else if (response.Code == 403) {
        err = apihelper.NewAPIError("This action needs a valid WSSE header", response.Code, response.RawBody)
    } else if (response.Code == 400) {
        err = apihelper.NewAPIError("Http bad request", response.Code, response.RawBody)
    } else if (response.Code < 200) || (response.Code > 206) { //[200,206] = HTTP OK
            err = apihelper.NewAPIError("HTTP Response Not OK", response.Code, response.RawBody)
        }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }
    
    //returning the response
    var retVal interface{}
    err = json.Unmarshal(response.RawBody, &retVal)

    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil
}

