/*
 * magictelecomapi
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/23/2016
 */

package users


/*
 * Interface for the USERS_IMPL
 */
type USERS interface {
    GetAuthentications () (interface{}, error)
}

/*
 * Factory for the USERS interaface returning USERS_IMPL
 */
func NewUSERS() USERS {
    return &USERS_IMPL{}
}